spring: 
  application:
    name: TOKEN-DETOKEN-SERVICE
eureka: 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instanceId: token-detoken-service
    healthcheck: 
      enabled: true
server: 
  port: 9999